### PR TITLE
Add support for .org export

### PR DESCRIPTION
**Pull request by VitorGoatman**
I've began using Doom Emacs to edit code and write my stuff in org-mode, but I still like using Wordgrinder from time to time. I decided to add an org-mode exporter just so I can manipulate the resulting org-mode file in more interesting ways inside Emacs. It's nothing fancy, just an edited version of the markdown exporter as I don't know much lua.

The only issue I ran into was that wordgrinder exports seem to wrap the space after a word into the style of the word, which makes the output a little weird in org syntax and the buffer.

For example, the words below

> **bold** _italic_

will be translated as:

>`*bold * /italic /` 

If the extra space wasn't there Emacs would render the words' styles correctly, like so

>\***bold**\* _/italic/_

Other than this little problem, it works just fine. I even made it add an extra `#+TITLE: (document title here)` at the top of the file.

### CODE REVIEW

**Comment by davidgiven** [comment]
Thanks very much! It mostly looks fine, but:

- I think you've forgotten to check in the change to `build.lua` to build your new source file;
- could you add a test, please? You can copy `tests/export-to-markdown.lua`; the logic should be fairly obvious (the test will also need to be listed in `build.lua`.

**Comment by VitorGoatman** [comment]
There we go, that should be everyhing

**Comment by davidgiven** [comment]
Hmm. The tests actually fail.

```
Lua error: tests/export-to-org.lua:59: attempt to call field 'ExportToOrgString' (a nil value)
stack traceback:
	tests/export-to-org.lua:59: in function 'f'
	[string "src/lua/main.lua"]:303: in function 'fn'
	[string "src/lua/utils.lua"]:389: in function 'ParseArguments'
	[string "src/lua/main.lua"]:365: in function <[string "src/lua/main.lua"]:239>
```

It looks like the build system doesn't consider test failures to be a build failure! Wow. That'll be my fault and I'll look into it, but can you check out the test failure above? Just doing `make` should run the tests from the command line.

**Comment by davidgiven** [comment]
The build problem with tests is fixed, if you update from master.

**Comment by davidgiven** [comment]
Oops! I dropped this one completely on the floor... I've merged it. Thanks!

**Pull request merged**
