### PR TITLE
Check for a Redhat-style system. Use 'lua' instead of 'lua5.2' if so.

### LINKED ISSUE #23: Makefile needs small modification to compile on Fedora.
Hello,

In fedora lua is called by "lua" not "lua5.2", so in order for it to compile it is necessary to change the include statement for lua in the makefile. While I really have no idea, I imagine that this is probably the case for RHEL and CentOS as well. Perhaps it is worth adding a note to the readme?

### PR DESCRIPTION
**Pull request by funnelfiasco**
Fixes #23. (Note that this patch is included in the forthcoming Fedora
package)

### CODE REVIEW

**Comment by davidgiven** [comment]
Is that guaranteed to be lua5.2? How does Red Hat distinguish between 5.1 and 5.3?

**Comment by funnelfiasco** [comment]
That's a very good question. Let me try it on a few other versions and see.

**Comment by funnelfiasco** [comment]
So it looks like Red Hat/Fedora will always use `lua` for the default lua version. Older versions will be in the `compat-lua-*` packages.

So for example on Fedora 25, the lua (lua-libs, specficially) package, which is currently 5.3, provides `/usr/lib/liblua.so` which is a symlink to `/usr/lib/liblua-5.3.so`. The lua-compat package provides `/usr/lib/lua-5.1.so`.

There is no lua 5.2 available on Fedora 25, at least. But the MR matches the general pattern for library versions (which is to not use them). If there comes a time when a specific version is required, then we may have to reconsider.

But as I type this, I wonder if that's related to the problem in #39. I'll go find out.

**Comment by davidgiven** [comment]
Okay, so as discovered in #39... WordGrinder doesn't work with Lua 5.3, which means it's really important _not_ to use the default Lua version. Therefore the Fedora packaging needs to explicitly depend on and reference the Lua 5.2 libraries.

If F25 doesn't have Lua 5.2... does it have LuaJIT? Or Lua 5.1? I _think_ WordGrinder still works against Lua 5.1, but it'll need testing.

**Comment by funnelfiasco** [comment]
I had some build troubles with 5.1, but LuaJIT seems to work. I'll let Bryan test the new build and if it works, I'll update the pull request with a working version.

**Comment by semioticrobotic** [comment]
Happy to, @funnelfiasco. Linkage?

**Comment by funnelfiasco** [comment]
Oh hey @semioticrobotic! I emailed your work address because it's all I had. Here's a link to the new RPM

https://bcotton.fedorapeople.org/wordgrinder/wordgrinder-0.6-2.fc25.x86_64.rpm

**Comment by semioticrobotic** [comment]
Ah! Sorry, @funnelfiasco. Should have checked my email first. Will get on it!

**Comment by semioticrobotic** [comment]
Works like a charm, @funnelfiasco! Thanks so much.

**Comment by funnelfiasco** [comment]
I've updated my branch with a version that uses lua JIT.

**Comment by funnelfiasco** [comment]
I finally got a package that both successfully builds on Fedora and meets the policy requirements. However, it looks fairly different from the current state of this pull request. So I'm going to close this and start a new one from scratch.

**Comment by davidgiven** [comment]
FWIW, WordGrinder is now _supposed_ to work with 5.3.

**Comment by davidgiven** [comment]
...and the build system should now be rewritten to autodetect all this stuff and work out of the box (even on OSX). Any chance you could give head of git a try and let me know what it does on Fedora?

**Comment by funnelfiasco** [comment]
@davidgiven from HEAD:
```
ninja: error: 'bin/xwordgrinder-lua-5.2-x11-release', needed by 'all', missing and no known rule to make it
make: *** [Makefile:53: all] Error 1
```

Also, the README doesn't reflect the new ninja build requirement.

**Comment by davidgiven** [comment]
Totally forgot to rewrite the README --- this evening's job.

Could you attach the build log? It sounds like it's confused about whether Lua and Xlib exists.

**Comment by funnelfiasco** [comment]
No log written:
```
1031 bcotton@normal ~/devel/wordgrinder-upstream ]$ make -j
Bootstrapping build
Windows toolchain: not found
Curses package 'ncursesw': not found
FreeType2: found
Lua package 'lua-5.2': not found
Lua package 'lua-5.1': found
Lua package 'lua-5.3': not found
Lua package 'luajit': found
ninja: error: 'bin/xwordgrinder-lua-5.2-x11-release', needed by 'all', missing and no known rule to make it
make: *** [Makefile:53: all] Error 1
[1032 bcotton@normal ~/devel/wordgrinder-upstream ]$ find . -mmin -2
./.git
./.git/index
```

**Comment by davidgiven** [comment]
Ah, I know what's happening --- it's detected which Luas you have, but the build configuration is set to always try to install the Lua 5.2 version. As you don't have that installed, it hasn't been built.

Change the settings of LUA_PACKAGE in the makefile to 'internallua' (or 'lua-5.1' or 'luajit' for a dynamic link).

The default needs changing, _and_ it needs a better error message when it's set wrong.

**Comment by funnelfiasco** [comment]
Builds both xwordgrinder and curses wordgrinder (once I actually install the ncurses-devel package, oops). Looks good to me. I'll still need to monkey around with my RPM spec file a bit to get it updated for the new build system, but that shouldn't require anything on your end.

**Comment by davidgiven** [comment]
Both Makefile and README are updated. Thanks!

**Pull request closed without merging**
