### PR TITLE
Markdown Support

### PR DESCRIPTION
**Pull request by NRauh**
Made the ability to export documents in Markdown format.

Some things to note: Both list types, and indented text make a bulleted list and quote respectively. Preformatted text makes a code block, and raw makes inline pre-text.

I decided it would be better to make a new line after each return rather than make people add a blank line between paragraphs to make a line break in Markdown. Because of this, if someone has part of their document paragraph styles like
```
Plain text paragraph
Raw paragraph
Plain text
```
It'll look like...

Example

`raw text`
with paragraph

...instead of: Example `raw text` with paragraph.

### CODE REVIEW

**Comment by davidgiven** [comment]
Awesome, thanks! (I've been vaguely planning to do this...)

It's possible to omit the newline before and after raw text paragraphs; the html exporter does something like this --- just suppress it if currentpara or newpara is "RAW".

Also, we don't seem to be escaping the Markdown special characters. Putting _ or * inside italic or bold does weird things, and the section on README.md with the HTML tags in it gets the Markdown renderer very, very confused.

I also note that the Markdown renderer doesn't support things like "123**4 5**67". The cheap fix here is to output the tags as <b> and </b> rather than **, but that's not very human readable. Who's the target audience here?

**Comment by davidgiven** [comment]
Incidentally, I've added a really basic framework to allow exporters to be tested:

https://github.com/davidgiven/wordgrinder/commit/08f34324fead23e1b77e76904d9abe158556e075

It sounds like Markdown is sufficiently hairy that tests would be useful.

(Also I notice that in my previous post, Github rendered the Markdown examples. Sigh. And it rendered them differently to the renderer I was experimenting with. Also sigh. That last bold 'and' should be surrounded in HTML tags. Is there a canonical renderer somewhere?)

**Comment by NRauh** [comment]
I made a few general changes

- Swapped the functionality of pre and raw, because I thought their functions would be better suited the other way around. Also I switched to four spaces instead of \`\`\`
- Made it so it adds a new line at the end of the document
- Added a space between the hash on the header, because it looks like it's a bit more style conforming

> we don't seem to be escaping the Markdown special characters.

Looks like I forgot to escape \* and \_. I'm escaping them now, and it looks like it's working in and out of bold and italic.

On that note, I noticed that some people put underscore and others put a single asterisk for italic text. I personally think an underscore looks better reading it, but if you'd prefer it the other way, or if it usually makes a difference when converting Markdown, I can switch it.

> Who's the target audience here?

Not sure if you were asking as a general question, or because of those problems. But I figure that the target audience would be writers/bloggers who can use Markdown for their things. Or maybe people who want to want to keep a plain text archive of something with very basic formatting.

**Comment by davidgiven** [comment]
Yikes, sorry! I completely forgot about this...

Thanks for the changes, but it looks like there are still some unescaped characters. I converted README.wg and pasted it into a github gist comment as a cheap way of rendering it:

https://gist.github.com/davidgiven/91750dbcdd73be10761d

I see you're escaping > but not <?

**Comment by NRauh** [comment]
Sorry I was busy then I forgot to take a look. I figured out what was going wrong though. I wasn't thinking about things like the html tags in a paragraph like what's in the read me file. So I made the assumption that \> would only be used in a situation where it's just by itself, not like \<tag\>. The problem was with GitHub's markdown rendering, since it takes tags as actual formatting, and it doesn't look like that's universal.

I was only escaping \> because I didn't think a markdown renderer would render things differently if there was a \<.

I added escaping of \< and also removed the space requirement for \> just in case.

**Comment by davidgiven** [comment]
Looking good!

https://gist.github.com/davidgiven/1aba97e96a9b8f9b573b

Of course, MarkDown is so fuzzily defined that there's no such thing as conformance, but I reckon this is easily good enough.

Thanks --- merged!

**Pull request merged**
